# Generated by Django 4.0.4 on 2022-11-26 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_image')),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turf_image', to='api.turf')),
            ],
        ),
    ]
