# Generated by Django 4.0.4 on 2022-12-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_image_image_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(blank=True, max_length=999, null=True),
        ),
    ]
